--!strict
-- PlantDefinitions.lua
-- Prototype crop data for "Urban Plant Tycoon Berlin"
-- Month mapping: 1=Jan, 2=Feb, ... 12=Dec

export type PlantDefinition = {
	id: string,
	displayName: string,
	idealFieldType: string,
	plantWindowMonths: {number},
	harvestWindowMonths: {number},
	baseGrowMonths: number,
	baseYield: number,
	seedCost: number,
	sellPrice: number,
}

local PlantDefinitions: {[string]: PlantDefinition} = {
	TOMATO = {
		id = "TOMATO",
		displayName = "Tomate",
		idealFieldType = "SUN_WET",
		plantWindowMonths = {3, 4, 5},
		harvestWindowMonths = {7, 8, 9},
		baseGrowMonths = 3,
		baseYield = 6,
		seedCost = 24,
		sellPrice = 15,
	},
	STRAWBERRY = {
		id = "STRAWBERRY",
		displayName = "Erdbeere",
		idealFieldType = "SUN_WET",
		plantWindowMonths = {4, 8},
		harvestWindowMonths = {5, 6},
		baseGrowMonths = 4,
		baseYield = 5,
		seedCost = 20,
		sellPrice = 18,
	},
	PUMPKIN = {
		id = "PUMPKIN",
		displayName = "Kürbis",
		idealFieldType = "SUN_WET",
		plantWindowMonths = {5, 6},
		harvestWindowMonths = {9, 10},
		baseGrowMonths = 4,
		baseYield = 7,
		seedCost = 26,
		sellPrice = 20,
	},
	POTATO = {
		id = "POTATO",
		displayName = "Kartoffel",
		idealFieldType = "SUN_DRY",
		plantWindowMonths = {4},
		harvestWindowMonths = {8, 9},
		baseGrowMonths = 4,
		baseYield = 7,
		seedCost = 16,
		sellPrice = 11,
	},
	CARROT = {
		id = "CARROT",
		displayName = "Möhre",
		idealFieldType = "SUN_DRY",
		plantWindowMonths = {3, 4, 5},
		harvestWindowMonths = {6, 7, 8, 9, 10},
		baseGrowMonths = 3,
		baseYield = 6,
		seedCost = 12,
		sellPrice = 9,
	},
	ONION = {
		id = "ONION",
		displayName = "Zwiebel",
		idealFieldType = "SUN_DRY",
		plantWindowMonths = {3, 4},
		harvestWindowMonths = {7, 8, 9},
		baseGrowMonths = 3,
		baseYield = 6,
		seedCost = 13,
		sellPrice = 10,
	},
	SPINACH = {
		id = "SPINACH",
		displayName = "Spinat",
		idealFieldType = "SHADE_WET",
		plantWindowMonths = {3, 4, 8},
		harvestWindowMonths = {4, 5, 9},
		baseGrowMonths = 2,
		baseYield = 5,
		seedCost = 10,
		sellPrice = 9,
	},
	LAMB_LETTUCE = {
		id = "LAMB_LETTUCE",
		displayName = "Feldsalat",
		idealFieldType = "SHADE_WET",
		plantWindowMonths = {8, 9},
		harvestWindowMonths = {10, 11, 12, 1, 2, 3},
		baseGrowMonths = 3,
		baseYield = 5,
		seedCost = 11,
		sellPrice = 11,
	},
	BRUSSELS_SPROUT = {
		id = "BRUSSELS_SPROUT",
		displayName = "Rosenkohl",
		idealFieldType = "SHADE_WET",
		plantWindowMonths = {4, 5},
		harvestWindowMonths = {11, 12, 1, 2},
		baseGrowMonths = 5,
		baseYield = 7,
		seedCost = 18,
		sellPrice = 17,
	},
	KALE = {
		id = "KALE",
		displayName = "Grünkohl",
		idealFieldType = "SHADE_DRY",
		plantWindowMonths = {5, 6},
		harvestWindowMonths = {11, 12, 1, 2},
		baseGrowMonths = 5,
		baseYield = 7,
		seedCost = 15,
		sellPrice = 14,
	},
	PEA = {
		id = "PEA",
		displayName = "Erbse",
		idealFieldType = "SHADE_DRY",
		plantWindowMonths = {3, 4},
		harvestWindowMonths = {6, 7},
		baseGrowMonths = 3,
		baseYield = 6,
		seedCost = 12,
		sellPrice = 10,
	},
	BUSH_BEAN = {
		id = "BUSH_BEAN",
		displayName = "Buschbohne",
		idealFieldType = "SHADE_DRY",
		plantWindowMonths = {5, 6},
		harvestWindowMonths = {7, 8, 9},
		baseGrowMonths = 3,
		baseYield = 6,
		seedCost = 13,
		sellPrice = 11,
	},
}

return PlantDefinitions
